CREATE TABLE VEMSER_DAYVIDSON.ESTUDANTE(
	id_estudante NUMBER NOT NULL,
	nome VARCHAR(200) NOT NULL,
	data_nascimento DATE NOT NULL,
	nr_matricula NUMBER(10) UNIQUE NOT NULL,
	ativo CHAR(1),
	PRIMARY KEY(id_estudante)
);

CREATE SEQUENCE VEMSER_DAYVIDSON.SEQ_ESTUDANTE
START WITH 1
INCREMENT BY 1 NOCYCLE NOCACHE;

INSERT INTO VEMSER_DAYVIDSON.ESTUDANTE 
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Joao Joa', TO_DATE('03-04-1990', 'dd-mm-yyyy'), 1001, 'S' );

INSERT INTO VEMSER_DAYVIDSON.ESTUDANTE 
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Dayvidson', TO_DATE('03-04-1990', 'dd-mm-yyyy'), 1002, 'S' )

INSERT INTO VEMSER_DAYVIDSON.ESTUDANTE 
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Fernanda', TO_DATE('03-04-1990', 'dd-mm-yyyy'), 1003, 'S' )

INSERT INTO VEMSER_DAYVIDSON.ESTUDANTE 
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Alfe', TO_DATE('03-04-1990', 'dd-mm-yyyy'), 1004, 'N' )

INSERT INTO VEMSER_DAYVIDSON.ESTUDANTE 
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Gilberto', TO_DATE('03-04-1990', 'dd-mm-yyyy'), 1005, 'S' )

INSERT INTO VEMSER_DAYVIDSON.ESTUDANTE 
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Ralph', TO_DATE('03-04-1990', 'dd-mm-yyyy'), 1006, 'N' )

INSERT INTO VEMSER_DAYVIDSON.ESTUDANTE 
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Bob', TO_DATE('03-04-1990', 'dd-mm-yyyy'), 1007, 'S' )

INSERT INTO VEMSER_DAYVIDSON.ESTUDANTE 
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Silva', TO_DATE('03-04-1990', 'dd-mm-yyyy'), 1008, 'N' )

INSERT INTO VEMSER_DAYVIDSON.ESTUDANTE 
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Anakim', TO_DATE('03-04-1990', 'dd-mm-yyyy'), 1009, 'S' )

INSERT INTO VEMSER_DAYVIDSON.ESTUDANTE 
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Luke', TO_DATE('03-04-1990', 'dd-mm-yyyy'), 1010, 'N' );

INSERT INTO VEMSER_DAYVIDSON.ESTUDANTE 
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.NEXTVAL, 'Rodolfo', TO_DATE('03-04-1990', 'dd-mm-yyyy'), 1011, 'N' );

SELECT * FROM VEMSER_DAYVIDSON.ESTUDANTE;

CREATE TABLE VEMSER_DAYVIDSON.PAIS (
                ID_PAIS NUMBER(38) PRIMARY KEY NOT NULL,
                NOME VARCHAR(50) NOT NULL
);

CREATE SEQUENCE seq_pais
START WITH 1
INCREMENT BY 1 NOCYCLE NOCACHE;

CREATE TABLE VEMSER_DAYVIDSON.ESTADO (
                ID_ESTADO NUMBER(38) PRIMARY KEY NOT NULL,
                ID_PAIS NUMBER(38) NOT NULL,
                NOME VARCHAR2(50) NOT NULL,
                CONSTRAINT FK_ID_PAIS FOREIGN KEY(ID_PAIS) REFERENCES PAIS (ID_PAIS)
);

CREATE SEQUENCE seq_estado
START WITH 1
INCREMENT BY 1 NOCYCLE NOCACHE;

CREATE TABLE VEMSER_DAYVIDSON.CIDADE (
                ID_CIDADE NUMBER(38) NOT NULL,
                ID_ESTADO NUMBER(38) NOT NULL,
                NOME VARCHAR2(50) NOT NULL,
                CONSTRAINT PK_CIDADE PRIMARY KEY (ID_CIDADE, ID_ESTADO),
                CONSTRAINT FK_ID_ESTADO FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);

CREATE SEQUENCE seq_cidade
START WITH 1
INCREMENT BY 1 NOCYCLE NOCACHE;

CREATE TABLE VEMSER_DAYVIDSON.BAIRRO (
                ID_BAIRRO NUMBER(38) NOT NULL,
                ID_CIDADE NUMBER(38) NOT NULL,
                ID_ESTADO NUMBER(38) NOT NULL,
                NOME VARCHAR2(50) NOT NULL,
                CONSTRAINT PK_BAIRRO PRIMARY KEY (ID_BAIRRO, ID_CIDADE),
                CONSTRAINT FK_ID_CIDADE FOREIGN KEY (ID_CIDADE, ID_ESTADO) REFERENCES CIDADE (ID_CIDADE, ID_ESTADO)
);

CREATE SEQUENCE seq_bairro
START WITH 1
INCREMENT BY 1 NOCYCLE NOCACHE;

CREATE TABLE VEMSER_DAYVIDSON.Endereco (
                ID_ENDERECO NUMBER(38) PRIMARY KEY NOT NULL,
                ID_BAIRRO NUMBER(38) NOT NULL,
                ID_CIDADE NUMBER(38) NOT NULL,
                LOGRADOURO VARCHAR2(255) NOT NULL,
                NUMERO NUMBER(38) NOT NULL,
                COMPLEMENTO VARCHAR2(100),
                CEP CHAR(9),
                CONSTRAINT FK_ID_ENDERECO_BAIRRO FOREIGN KEY (ID_BAIRRO, ID_CIDADE) REFERENCES BAIRRO (ID_BAIRRO, ID_CIDADE)

);

CREATE SEQUENCE seq_endereco
START WITH 1
INCREMENT BY 1 NOCYCLE NOCACHE;

INSERT INTO VEMSER_DAYVIDSON.PAIS (ID_PAIS, NOME) VALUES (seq_pais.nextval, 'Brasil');
INSERT INTO VEMSER_DAYVIDSON.PAIS (ID_PAIS, NOME) VALUES (seq_pais.nextval, 'Estados Unidos');


INSERT INTO VEMSER_DAYVIDSON.ESTADO (ID_ESTADO, ID_PAIS, NOME) VALUES (seq_estado.nextval, 1, 'São Paulo');
INSERT INTO VEMSER_DAYVIDSON.ESTADO (ID_ESTADO, ID_PAIS, NOME) VALUES (seq_estado.nextval, 1, 'Rio de Janeiro');

INSERT INTO VEMSER_DAYVIDSON.ESTADO (ID_ESTADO, ID_PAIS, NOME) VALUES (seq_estado.nextval, 2, 'Minas Gerais');
INSERT INTO VEMSER_DAYVIDSON.ESTADO (ID_ESTADO, ID_PAIS, NOME) VALUES (seq_estado.nextval, 2, 'Paraná');


INSERT INTO VEMSER_DAYVIDSON.CIDADE (ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_cidade.nextval, 1, 'São Paulo');
INSERT INTO VEMSER_DAYVIDSON.CIDADE (ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_cidade.nextval, 1, 'São Bernardo do Campo');

INSERT INTO VEMSER_DAYVIDSON.CIDADE (ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_cidade.nextval, 2, 'Fortaleza');
INSERT INTO VEMSER_DAYVIDSON.CIDADE (ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_cidade.nextval, 2, 'Manaus');

INSERT INTO VEMSER_DAYVIDSON.CIDADE (ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_cidade.nextval, 3, 'Goiânia');
INSERT INTO VEMSER_DAYVIDSON.CIDADE (ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_cidade.nextval, 3, 'Porto Alegre');

INSERT INTO VEMSER_DAYVIDSON.CIDADE (ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_cidade.nextval, 4, 'Curitiba');
INSERT INTO VEMSER_DAYVIDSON.CIDADE (ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_cidade.nextval, 4, 'Salvador');


INSERT INTO VEMSER_DAYVIDSON.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_bairro.nextval, 1, 1, 'Samapi');
INSERT INTO VEMSER_DAYVIDSON.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_bairro.nextval, 1, 1, 'Estradinha');

INSERT INTO VEMSER_DAYVIDSON.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_bairro.nextval, 2, 1, 'Pântano do Sul');
INSERT INTO VEMSER_DAYVIDSON.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_bairro.nextval, 2, 1, 'Centro');

INSERT INTO VEMSER_DAYVIDSON.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_bairro.nextval, 3, 2, 'Centro');
INSERT INTO VEMSER_DAYVIDSON.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_bairro.nextval, 3, 2, 'Brasília');

INSERT INTO VEMSER_DAYVIDSON.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_bairro.nextval, 4, 2, 'Plano Diretor Sul');
INSERT INTO VEMSER_DAYVIDSON.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_bairro.nextval, 4, 2, 'São Valentim');

INSERT INTO VEMSER_DAYVIDSON.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_bairro.nextval, 5, 3, 'Jardim Tijuca');
INSERT INTO VEMSER_DAYVIDSON.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_bairro.nextval, 5, 3, 'Núcleo Habitacional Buriti');

INSERT INTO VEMSER_DAYVIDSON.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_bairro.nextval, 6, 3, 'Vila Vilas Boas');
INSERT INTO VEMSER_DAYVIDSON.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_bairro.nextval, 6, 3, 'Goiabal');

INSERT INTO VEMSER_DAYVIDSON.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_bairro.nextval, 7, 4, 'Jardim Independência');
INSERT INTO VEMSER_DAYVIDSON.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_bairro.nextval, 7, 4, 'Central');

INSERT INTO VEMSER_DAYVIDSON.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_bairro.nextval, 8, 4, 'Centro');
INSERT INTO VEMSER_DAYVIDSON.BAIRRO (ID_BAIRRO, ID_CIDADE, ID_ESTADO, NOME) VALUES (seq_bairro.nextval, 8, 4, 'Loteamento Della Rocha');



INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 1, 1, 'Rua José Palomo', 1254, NULL,'04532-040');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 1, 1, 'Rua Marechal Deodoro', 548, NULL,'40260-210');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 2, 1, 'Travessa Álvaro Maia', 254, NULL,'05736-110');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 2, 1, 'Rua Júlio Prestes', 789, NULL,'41230-335');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 3, 2, 'Rua Manoel Brito de Oliveira', 98, 'Apartamento 32','02650-060');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 3, 2, 'Rua Leonardo da Vinci', 751, NULL,'41490-214');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 4, 2, 'Travessa Lajes', 254, NULL,'04733-000');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 4, 2, 'Rua Almerindo dos Santos', 444, NULL,'41925-155');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 5, 3, 'Rua 36', 854, NULL,'41760-035');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 5, 3, 'Rua 64', 77, 'Apartamento 54','41245-810');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 6, 3, 'Alameda Elisa Quintal', 254, NULL,'40750-255');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 6, 3, 'Quadra QR 602 Conjunto 1', 885, NULL,'40750-255');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 7, 4, 'Rua Rio de Janeiro', 77, 'Apartamento 90','40830-540');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 7, 4, 'Rua Professor Luiz Cerqueira Monteiro', 85, 'Apartamento 77','40830-540');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 8, 4, 'Rua Domingos Lopes', 377, NULL,'40221-465');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 8, 4, 'Rua Paraíso', 555, NULL,'41211-023');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 9, 5, 'Avenida Fernandes Lima', 1239, NULL,'100014333');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 9, 5, 'Rua José Amaro da Cunha', 1555, NULL,'100014333');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 10, 5, 'Rua Arnaldo Estevão de Figueiredo', 1900, NULL,'063907847');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 10, 5, 'Rua Visconde de Pedra Branca', 1874, NULL,'063907847');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 11, 6, 'Rua Goiás', 6984, NULL,'100015431');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 11, 6, 'Rua Iporá', 6400, NULL,'100015431');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 12, 6, 'Rua Geraldo Vidueira Guerra', 777, NULL,'10013811');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 12, 6, 'Rua Cândido Ribeiro Esteves', 13, NULL,'10013811');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 13, 7, 'Avenida Dom Frederico Costa', 1239, NULL,'11011132');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 13, 7, 'Quadra Quadra 550', 1240, NULL,'11011132');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 14, 7, 'Rua Rio Marie', 1900, NULL,'10013844');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 14, 7, 'Avenida Dom Antônio Barbosa', 1903, NULL,'1013844');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 15, 8, 'Rua Milton Campos', 6984, NULL,'1005012');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 15, 8, 'Rua Joana de Castro Brandão', 6999, NULL,'1015012');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 16, 8, 'Rodovia Curiau', 777, NULL,'10012006');

INSERT INTO VEMSER_DAYVIDSON.ENDERECO (ID_ENDERECO, ID_BAIRRO, ID_CIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, CEP)
VALUES (seq_endereco.nextval, 16, 8, 'Rua São Luís', 778, NULL,'1012006');


SELECT * FROM VEMSER_DAYVIDSON.PAIS
ORDER BY NOME DESC;

SELECT
	LOGRADOURO,
	CEP
FROM VEMSER_DAYVIDSON.ENDERECO
WHERE LOWER(LOGRADOURO) LIKE 'a%';

SELECT 
	CEP
FROM VEMSER_DAYVIDSON.ENDERECO
WHERE CEP LIKE '%0';

SELECT *
FROM VEMSER_DAYVIDSON.ENDERECO
WHERE NUMERO BETWEEN 1 AND 100;

SELECT *
FROM VEMSER_DAYVIDSON.ENDERECO
WHERE UPPER(LOGRADOURO) LIKE 'RUA%'
ORDER BY CEP DESC;

SELECT 
	COUNT(ID_ENDERECO)
FROM VEMSER_DAYVIDSON.ENDERECO;

SELECT 
	COUNT(ID_ENDERECO),
	ID_CIDADE 
FROM VEMSER_DAYVIDSON.ENDERECO
GROUP BY ID_CIDADE;


