-- Ex1: RIGHT JOIN PESSOA -> CONTATO
SELECT P.ID_PESSOA AS COD_PESSOA
	 , P.NOME 
	 , C.ID_CONTATO AS COD_CONTATO
	 , C.ID_PESSOA  AS COD_PESSOA_CONTATO
	 , C.NUMERO 
  FROM VEM_SER.PESSOA P
 RIGHT JOIN VEM_SER.CONTATO C ON (P.ID_PESSOA = C.ID_PESSOA);
	

-- Ex2: RIGHT JOIN PESSOA -> PESSOA_X_PESSOA_ENDERECO -> ID_ENDERECO
SELECT P.ID_PESSOA AS Cod_pessoa
	 , P.NOME 
	 , EP.ID_ENDERECO AS Cod_Endereco
	 , EP.LOGRADOURO AS Rua
  FROM VEM_SER.PESSOA P
 RIGHT JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO PXPE ON (P.ID_PESSOA = PXPE.ID_PESSOA)
 RIGHT JOIN VEM_SER.ENDERECO_PESSOA EP ON (PXPE.ID_ENDERECO = EP.ID_ENDERECO);
	

-- Ex3: RIGHT JOIN PESSOA -> CONTATO 
--				 | PESSOA -> PESSOA_X_PESSOA_ENDERECO 
-- 				 | PESSOA_X_PESSOA_ENDERECO -> ENDERECO_PESSOA 

SELECT P.ID_PESSOA AS COD_PESSOA
     , P.NOME 
     , P.CPF 
     , C.ID_CONTATO AS COD_CONTATO
     , C.ID_PESSOA AS COD_PESSOA_CONTATO
     , C.NUMERO 
     , EP.ID_ENDERECO AS COD_PESSOA_ENDERECO
     , EP.LOGRADOURO AS RUA
  FROM VEM_SER.PESSOA P 
 RIGHT JOIN VEM_SER.CONTATO C ON (P.ID_PESSOA = C.ID_PESSOA)
 RIGHT JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO PXPE ON (P.ID_PESSOA = PXPE.ID_PESSOA)
 RIGHT JOIN VEM_SER.ENDERECO_PESSOA EP ON (PXPE.ID_ENDERECO = EP.ID_ENDERECO);
	
	

-- Ex4: FULL JOIN PESSOA -> CONTATO 
SELECT P.ID_PESSOA AS COD_PESSOA
	 , P.NOME 
	 , C.ID_CONTATO AS COD_CONTATO
	 , C.ID_PESSOA  AS COD_PESSOA_CONTATO
	 , C.NUMERO 
  FROM VEM_SER.PESSOA P 
  FULL JOIN VEM_SER.CONTATO C ON (P.ID_PESSOA = C.ID_PESSOA);


-- Ex5: FULL JOIN PESSOA -> PESSOA_X_PESSOA_ENDERECO -> ENDERECO_PESSOA 
SELECT P.ID_PESSOA AS Cod_pessoa
	 , P.NOME 
	 , EP.ID_ENDERECO AS Cod_Endereco
	 , EP.LOGRADOURO AS Rua
  FROM VEM_SER.PESSOA P 
  FULL JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO PXPE ON (P.ID_PESSOA = PXPE.ID_PESSOA)
  FULL JOIN VEM_SER.ENDERECO_PESSOA EP ON (EP.ID_ENDERECO = PXPE.ID_ENDERECO);
 
 
-- Ex6: FULL JOIN PESSOA -> CONTATO
--			 	  PESSOA -> PESSOA_X_PESSOA_ENDERECO
-- 				  PESSOA_X_PESSOA_ENDERECO -> ENDERECO_PESSOA
 SELECT P.ID_PESSOA AS COD_PESSOA
      , P.NOME 
      , P.CPF 
      , C.ID_CONTATO AS COD_CONTATO
      , C.ID_PESSOA AS COD_PESSOA_CONTATO
      , C.NUMERO 
      , EP.ID_ENDERECO AS COD_PESSOA_ENDERECO
      , EP.LOGRADOURO AS RUA
   FROM VEM_SER.PESSOA P 
   FULL JOIN VEM_SER.CONTATO C ON (P.ID_PESSOA = C.ID_PESSOA)
   FULL JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO PXPE ON (P.ID_PESSOA = PXPE.ID_PESSOA)
   FULL JOIN VEM_SER.ENDERECO_PESSOA EP ON (PXPE.ID_ENDERECO = EP.ID_ENDERECO);
 

-- Ex7: EXISTS -> PESSOAS COM ENDERECO
SELECT P.NOME
     , P.ID_PESSOA AS COD_PESSOA
  FROM PESSOA P 
 WHERE EXISTS (SELECT PXPE.ID_PESSOA
					FROM PESSOA_X_PESSOA_ENDERECO PXPE
					WHERE PXPE.ID_PESSOA = P.ID_PESSOA);
	
				
-- Ex8: ID_PESSOA | NOME | ID_ENDERECO | LOGRADOURO
SELECT P.ID_PESSOA 
	 , P.NOME 
	 , EP.ID_ENDERECO 
	 , EP.LOGRADOURO 
  FROM VEM_SER.PESSOA P
  FULL JOIN PESSOA_X_PESSOA_ENDERECO PXPE ON (P.ID_PESSOA = PXPE.ID_PESSOA)
  FULL JOIN ENDERECO_PESSOA EP ON (PXPE.ID_ENDERECO = EP.ID_ENDERECO);
